version: '3.8'

services:
  my-postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./DockerFile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DATABASE_NAME=${DB_NAME}
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    ports:
      - "8000:8000"
    depends_on:
      - my-postgres


  celery_worker:
    build:
      context: .
      dockerfile: ./DockerFile
    command: celery -A cinema.celery worker --pool=solo --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - my-postgres

  celery_beat:
    build:
      context: .
      dockerfile: ./DockerFile
    command: celery -A cinema.celery beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - my-postgres

volumes:
  db_data:
