version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  celery_worker:
    build: .
    command: celery -A cinema.celery worker --pool=solo --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A cinema.celery beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
