# Generated by Django 5.0.3 on 2024-03-28 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='movie',
        ),
    ]
