# Generated by Django 5.0.3 on 2024-03-27 10:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('protagonists', models.JSONField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.FileField(upload_to='trailers/')),
                ('start_date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('ranking', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='Protagonists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
