# Generated by Django 5.0.3 on 2024-03-27 00:50

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('protagonists', jsonfield.fields.JSONField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('trailer', models.FileField(upload_to='trailers/')),
                ('start_date', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('ranking', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'movies',
                'ordering': ['ranking'],
            },
        ),
    ]
