name: Cinema CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r cinema/requirements.txt

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.ACTION_SECRET }}
          NAME: ${{ secrets.ACTION_SECRET }}
          USER: ${{ secrets.ACTION_SECRET }}
          PASSWORD: ${{ secrets.ACTION_SECRET }}
          HOST: ${{ secrets.ACTION_SECRET }}
          PORT: ${{ secrets.ACTION_SECRET }}
        run: pytest cinema/movies/tests.py


    
